name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  

jobs:
  terraform:
    name: 'Terraform'
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      #uses: hashicorp/terraform-github-action@main
      run: terraform init -migrate-state

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      #uses: hashicorp/terraform-github-action@main
      run: terraform apply -auto-approve


   