name: "Terraform"
 on:
 push :
 branches: ["main"]

 jobs:
 terraform :
   name: 'Terraform'
   env:
    AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY_ID: ${{secrets.SECRET_ACCESS_KEY}}
   runs-on : ubuntu-latest
   environment: production
     steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform Init
      uses: hashicorp/terraform-github-action@master
      run: terraform init

     - name: Terraform Plan
      uses: hashicorp/terraform-github-action@master
      run: terraform plan

